last fix of the night

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -157,6 +157,12 @@ jobs:
               fi
               url="https://github.com/themoeway/kaikki-to-yomitan/releases/download/${{needs.prepare.outputs.tag}}/kty-${source_iso}-${target_iso}-ipa.zip"
               wget -nv "$url"
+              if [ $? -eq 8 ]; then
+                  echo "404 Not Found for $url. Skipping."
+                  continue
+              elif [ $? -ne 0 ]; then
+                  echo "Error occurred with exit code $?."
+              fi
             done
           done
 
